### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by bytemanOKAY** [FiveMP/FiveMP-Issues#10]
Just like in SA-MP, if you open chat you can browse your input history with your up and down arrow buttons. I don't know how many inputs it remembers but even 4-5 would be great.

Thanks!

**Comment by MinionKingRules** [comment]
Agree on this one.

**Comment by No-Half-Measures** [comment]
I'm not sure if you guy's aware but open the chat input box your scroll wheel. I 'think' PageUp/Dwn works too but I've forgotten if we put that in or not.

**Comment by kamil445** [comment]
Yeah good idea m8 :)

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
