### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by MinionKingRules** [FiveMP/FiveMP-Issues#11]
1. Textdraw's Should be changed add a timer to them and removing the ids i prefer simply like this 

`TextDrawForPlayer(int playerid, float x, float y, string text, timer, scale)`
`TextDrawForAllr(float x, float y, string text, timer, scale)`

# Example.

`TextDrawForPlayer(playerid, 0.20, 0.10, "Hello", 5000, 3);`
`TextDrawForAll(0.20, 0.10, "Hello", 5000, 3);`

2. Interiors with ids cause ipl's are too much of a work simple funtion like this or similar
`SetPlayerInterior(playerid, world, interior id, enter x, enter y, enter z, exit x, exit y, exit z);`

as enter and exit float's are checkpoint co ordinates 
Note: i already saw interior ids on wiki so i assume it's already planned

3. Make a funtion of Vehicles health like 
`"SetVehicleHeatlh, GetVehicleHealth along with these SetVehicleEngineHealth, SetVehicleEngineHealth, GetVehicleFuelTankHealth & GetVehicleEngineHealth`

**Comment by No-Half-Measures** [comment]
Noted, In regards to the Get/SetVehicleHeatlh I will have to look into, if it's how I think its done then it'll be more likely to be something like Get/SetHealth as we have server entity's as mentioned a few times in our change logs at: https://changelog.five-multiplayer.net/
It just simplifies allot of functions that pretty much do the same thing.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
