### ISSUE TITLE
string.find should return nil but instead server crash.

### ISSUE THREAD

**Issue by St3fanNL** [FiveMP/FiveMP-Issues#12]
Hi,

I thought it was my code at first until i used the following example from a LUA tutorial site:
`s = "hello world"
  i, j = string.find(s, "hello")
  print(i, j)                      --> 1    5
  print(string.sub(s, i, j))       --> hello
  print(string.find(s, "world"))   --> 7    11
  i, j = string.find(s, "l")
  print(i, j)                      --> 3    3
  print(string.find(s, "lll",1))     --> nil`

The output is this:
> 2017-01-11 11:17:14,531 [INFO ] 1, 5
2017-01-11 11:17:14,532 [INFO ] hello
2017-01-11 11:17:14,533 [INFO ] 7, 11
2017-01-11 11:17:14,533 [INFO ] 3, 3
2017-01-11 11:17:14,535 [FATAL] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
    Invalid access to memory
    Program is trying to read an invalid (unallocated, deleted or corrupted) or inaccessible memory.

So I think there's some error with this function as it will crash as soon as its not found.

**Comment by Leka74** [comment]
The crash is happening because you are trying to print a nil value on this line:
`print(string.find(s, "lll",1))`

If you want to print a nil value, you need to convert the variable into a string using the tostring() function like this:
`print(tostring(string.find(s, "lll",1)))`
