### ISSUE TITLE
Detecting Input Events on Vehicles and Characters. And/Or Created Objects

### ISSUE THREAD

**Issue by taiven** [FiveMP/FiveMP-Issues#13]
It would be cool if we could detect input on Players, Vehicles and Objects..

Like a Left Click, Right Click type of deal. That's all.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
