### ISSUE TITLE
Client Side Scripting

### ISSUE THREAD

**Issue by TheKingTuro** [FiveMP/FiveMP-Issues#14]
**Client side scripting is my suggestion with an example.**

I know this is a super skilled team that could get things done, and I appreciate you guys dearly for your hard work. I have faith you guys could implement my suggestion which will make FIVEMP rain supreme over the other online networks. Making it possible to script Euphoria into your servers with client side scripting.

jedijosh920 
> Player reacts to bullets with native Euphoria like NPCs and will limp/hold stomach when injured and sometimes shoot on the ground when getting up.

https://www.youtube.com/watch?v=k9lpnsFh7yc

https://www.gta5-mods.com/scripts/bullet-impact

**Comment by No-Half-Measures** [comment]
I do not see this as something that Five Multiplayer should be adding as a Mod feature but rather as something someone can do with client scripting, maybe I'm wrong?

**Comment by TheKingTuro** [comment]
Yeah, pretty much. My suggestion is Client side scripting. All I showed was an example of what could be achieved with it.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
