### ISSUE TITLE
Keep GTA V directory clean

### ISSUE THREAD

**Issue by scythx** [FiveMP/FiveMP-Issues#15]
Ever heard about MTA:SA? that mod keep gta sa directory clean, they'll install anything (client-side script, mod) inside the installation directory (not inside gtasa directory of course).

So, would be good if FiveMP doesn't put anything FiveMP related file inside GTA V directory.

I'm not sure if FiveMP use ScriptHookV or not because i weren't played fivemp recently, busy irl and gta v deleted by accident, but OpenVHook should help.

**Comment by No-Half-Measures** [comment]
Hello, Yeah this is already our plan and we have already made progress on this with a few remaining files that need moving for 0.2a. Too add 0.2a onward will no-longer be using scripthook.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
