### ISSUE TITLE
MAC address

### ISSUE THREAD

**Issue by azzeroth** [FiveMP/FiveMP-Issues#16]
My suggestion is the MAC address.
Example:
We can get the mac address at player connect.
I think it's great idea for banning clients and for automatic login systems.

**Comment by No-Half-Measures** [comment]
There are better options imo and anyone can change their MAC address very easily thus making this not a viable option.

**Comment by azzeroth** [comment]
Yeah it's true, but why want to change?😂😃
If anyone want to bann a mac, then ban the "account", so i think is good idea.

**Comment by No-Half-Measures** [comment]
Thanks for the suggestion and we will consider it, I'm closing this ticket as the Issue Tracker here on GitHub will be used for Bug Reports only for here out.
If you have any new suggestions please post them on the forums:
https://forums.five-multiplayer.net/index.php?/forum/7-suggestions/
