### ISSUE TITLE
Game crashes on singleplayer loading completion

### ISSUE THREAD

**Issue by hannogrimm** [FiveMP/FiveMP-Issues#17]
Everytime I start FiveMP and the singleplayer is just about to begin, the FIveMP menu shows up, the game minimizes and gives me the following error:

ERROR: executing native 0x0888c3502dbbeef5 at address 00007FF70727F47B.

Singleplayer starts with a cutscene.

**Comment by No-Half-Measures** [comment]
@Svvite have you completed the GTAV prolouge in singleplayer?

**Comment by hannogrimm** [comment]
@No-Half-Measures No, I just did it, let's see if it works.

**Comment by hannogrimm** [comment]
Finishing Singleplayer Prologue fixed it =)
