### ISSUE TITLE
Error at Startup

### ISSUE THREAD

**Issue by YoussefMaged** [FiveMP/FiveMP-Issues#19]
So here's the scenario, I have Windows 10 and a Non-Steam GTA V version, when I turn on my PC and start to run FiveMP for the first time, everything goes fine till the loading/startup screen and when it comes to server lists the game tabs out and an error message appears saying this: http://imgur.com/3JzVCMT afterwards the game crashes, if I try to run FiveMP another time, just as the game starts, this error message appears: http://imgur.com/73otj0D though my game uses DirectX 11, I'm running both my game and FiveMP as administrator, please help, thanks in advance

**Comment by FiveMP** [comment]
Are you running the latest version of the game?

**Comment by YoussefMaged** [comment]
no 1.36

**Comment by FiveMP** [comment]
The modification only supports gameversion 877 or higher. If you're using 877, then please change `latestversion = true` to `latestversion = false` in your client's configuration file.

**Comment by YoussefMaged** [comment]
I did so, and I'm still getting the second error message that I've mentioned

**Comment by YoussefMaged** [comment]
And my game version is .877 yes

**Comment by FiveMP** [comment]
That's odd. Have you tried verifying your game files yet?

**Comment by YoussefMaged** [comment]
No, how do I do so?

**Comment by Adam-Ant** [comment]
Are you using the steam version of the game? If so, right click on the game, click properties,  local files tab, then verify integrity of game files....

**Comment by FiveMP** [comment]
Could you start the game like normal and change your game's settings to use `borderless windowed` instead of `fullscreen`? It's a known fix to the issue.

**Comment by YoussefMaged** [comment]
I reinstalled the game, changed latestversion to false, and run the game in borderless windowed, everything worked fine, thanks a lot :D

**Comment by FiveMP** [comment]
Awesome, glad to have helped. Have fun.
