### ISSUE TITLE
[suggestion] Stop synced data from stacking up if ping raises

### ISSUE THREAD

**Issue by ItsMos** [FiveMP/FiveMP-Issues#2]
Im using a program to measure data transfare, and i noticed when my ping gets high FiveMP uses all my bandwith (100 KB/s download) i guess its due the data being synced stack up waiting for me to receive it.

i don't notice this on other multiplayers such as MTA, a possible fix would be stopping packets when ping raises.
I'm not fluent in English but i hope i explained enough.

**Comment by No-Half-Measures** [comment]
We are dropping support 0.1b since we are putting full focus on 0.2a now which is a complete rewrite.
