### ISSUE TITLE
[API] API::World::LoadIPL not loading IPL

### ISSUE THREAD

**Issue by hannogrimm** [FiveMP/FiveMP-Issues#24]
Whatever IPL name I use, it won't load it for the player =)

**Comment by SamRobben** [comment]
Can you copy the code in? It should function.

- LaBloske

**Comment by hannogrimm** [comment]
`API::World::LoadIPL(entity, this->interior);`
with `this->interior` being a wstring, in my case: **"bh1_13_interior_v_hairdresser_milo_"** =)

**Comment by No-Half-Measures** [comment]
Curios how you know this is 'not working' ? This IPL is one of the ones that are typically already loaded in the world so loading it again would do nothing.

**Comment by FiveMP** [comment]
Turns out he didn't know that you have to teleport there as well, closed.
