### ISSUE TITLE
FiveMP Not Allowing Connection to Servers

### ISSUE THREAD

**Issue by MuhsinunC** [FiveMP/FiveMP-Issues#25]
Alright, so I have GTA V version 1.0.877.1, non-steam, on Windows 10 64bit. The game runs perfectly on it's own, but when I launch the FiveMP launcher, it starts & gives an error saying "Failed to initialize NativeHooks". Also, when I hit ok on that error window and then try to connect to a server, after a couple of seconds of my game being frozen, my game crashes.

Client.Config.ini:
`[Connection]
ip		= 127.0.0.1
port	= 2322
;pass = myserverpassword

[Information]
name		  = MuhsinunCool
latestversion = true`

If I change latestversion from true to false, then the FiveMP menu in game simply fails to show up. But with it set to true, I get the "Failed to initialize NativeHooks" error. I don't understand what could be wrong. I reinstalled FiveMP a few times now and also restarted my computer and tried restarting GTA V numerous time, but it simply doesn't work. I read the FAQ, asked other users in the #fivemp-support chat channel in the Discord server, but no one was able to help me successfully get my FiveMP up and running. I'm using the latest installation of FiveMP. All my scripts are removed from my GTA V root folder. My scripts folder is gone as well as my trainer and ScriptHookV & ScriptHookVDotNet. I also tried changing my username from MuhsinunCool to OhBoi to make it shorter, still no luck. Please help ASAP.

**Comment by SamRobben** [comment]
Do you have an official copy of GTA V?

- LaBloske

**Comment by MuhsinunC** [comment]
@samrobben Yup

**Comment by JLFSL** [comment]
Considering you point out that you have a legal copy of the game; why are you still on version 1.0.877.1? I'd recommend updating. Thought at this point; I doubt you have a legal copy.

**Comment by FiveMP** [comment]
Considering you point out that you have a legal copy of the game; why are you still on version 1.0.877.1? I'd recommend updating. Thought at this point; I doubt you have a legal copy.

**Comment by MuhsinunC** [comment]
@FiveMP it's not my computer. It's my friend's he has strict data limits. He won't let me update. :/

**Comment by No-Half-Measures** [comment]
Strict Data limits but yet was somehow able to download a 70gb game (around 65-67gb for 877)? If he's able to manage that then a couple extra gb isn't going to harm those 'limits'.
I recommend updating because latter on server owners will have control over if non latest build users can join or not and those top notch servers are more than likely going to disallow them.

**Comment by MuhsinunC** [comment]
@No-Half-Measures he installed the game a while ago & he used a disk. I'll talk to him about updating it, but I doubt he'll do it. :c :/ Thanks anyways.
