### ISSUE TITLE
[bug] GetPlayerPing returns the same value

### ISSUE THREAD

**Issue by ItsMos** [FiveMP/FiveMP-Issues#3]
Always returns one number and doesn't' update it.

**Comment by No-Half-Measures** [comment]
Sadly this is due to our 0.1 RakNet structure. In 0.2 this has completely changed so if its not working there I'll get it working there.


> We are dropping support for 0.1b since we have a full focus on 0.2a now which is a complete rewrite.
> I don't want to see any more 'issues' until 0.2a is out.
