### ISSUE TITLE
GetVehicleMod returning wrong values

### ISSUE THREAD

**Issue by theShuker** [FiveMP/FiveMP-Issues#4]
If you set a vehicle mod with any index to any value, all other indexes get same value

Reproducing:
SetVehicleMod(GetPlayerVehicleID(playerid), 0, 1)
GetVehicleMod(veh, 0) --returns 1
GetVehicleMod(veh, 1) -- returns 1, though it wasn't set at all

**Comment by No-Half-Measures** [comment]
![image](https://cloud.githubusercontent.com/assets/916733/21568507/2ff0b21e-cead-11e6-97b6-9716224c2d4a.png)
