### ISSUE TITLE
Bug with Vehicle World

### ISSUE THREAD

**Issue by mishagde** [FiveMP/FiveMP-Issues#5]
If the player in the car and at the same time changing the world for him and the vehicle, the vehicle is lost in an unknown world.

**Comment by No-Half-Measures** [comment]
![image](https://cloud.githubusercontent.com/assets/916733/21568512/425c0a16-cead-11e6-9382-edaf02db04a1.png)
We dropped support for 0.1 so we can focus on 0.2a
