### ISSUE TITLE
Add: addEventHandler/addEventHook

### ISSUE THREAD

**Issue by ItsMos** [FiveMP/FiveMP-Issues#6]
So instead of defining all the callbacks like we do now such as `function OnPlayerConnect()`
we would do
```Lua
addEventHandler('OnPlayerConnect', root, function (player) ... end)
```
the `root` here means anyone, and it can be replaced to trigger callback for a specific element/player, such as
```Lua
addEventHandler('OnPlayerEnterCheckpoint', myBlueCheckpoint,
  function (player)
    print('you entered my blue cp!')
  end)
```
For example: if you wanna limit the ammo of a buzzard machine gun, you shoot with `space`, so you do
```Lua
addEventHandler('OnPlayerEnterVehicle', myBuzzard, 
  function(player)
    addEventHandler('OnKeyDown', player, spaceKey, limitMachineGun)
  end)
```
This way we will not be stacking all our key bindings in one code block, also the server wont get bothered by everyone hitting space while they're not in a buzzard, just an example i thought of.

Edit: and server shouldn't crash when we don't define all callbacks.

**Comment by FiveMP** [comment]
Definitely something we'll add somewhere in 0.2, maybe even in 0.2a.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
