### ISSUE TITLE
Remove: SetSpawnPoint + SetPlayerRespawnTime

### ISSUE THREAD

**Issue by ItsMos** [FiveMP/FiveMP-Issues#7]
Replace it with `SpawnPlayer(player, x,y,z, [heading])`
as you might want to have different spawnpoints for different players/teams.

**Comment by No-Half-Measures** [comment]
Was already my plan to-do this as the current 0.1 system did not function as intended because of 3 factors, Ping, Server fps & sync overwriting what the server had set thus causing another death to happen.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
