### ISSUE TITLE
Adding Vehicles to GTA V

### ISSUE THREAD

**Issue by taiven** [FiveMP/FiveMP-Issues#8]
I thought it would be cool to add vehcles to GTA V,

Some people already [found out how to do it](http://www.lcpdfr.com/forums/topic/50909-adding-a-new-emergency-vehicle-is-possible-now/), but unfortunately it won't make the vehicles spawn in traffic.
The good news though <3 We don't care if they spawn in traffic because we have our own players and well You guys disabled traffic. I thought it would be cool if you made a way to do that with ease. I know its probably a long way out but I hope you consider it. Much better than replacing and much different than other mods who allow you to replace but not add.

Keep up the good work! Happy 2017
~Panda

**Comment by FiveMP** [comment]
Vehicle streaming has been thought of before. I don't think 0.2 will support it as it's not the easiest thing to implement.

**Comment by No-Half-Measures** [comment]
The GitHub Issue Tracker is going to be used for Bug Reports only from here on out.
If you wish to discuss more on this suggestion please go to the Forum topic below.
https://forums.five-multiplayer.net/index.php?/topic/12-suggestions-from-github/
